apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daily-quote-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: daily-quote-api-service
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: daily-quote-web-service
                port:
                  number: 80
